<Project Sdk="Microsoft.NET.Sdk.Worker">

    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <Nullable>enable</Nullable>
        <ImplicitUsings>enable</ImplicitUsings>
        <InvariantGlobalization>true</InvariantGlobalization>
        <PublishAot>true</PublishAot>
        <UserSecretsId>dotnet-Subscriber-43b6887b-cc74-4125-b9af-dd4f1c68985c</UserSecretsId>
        <RootNamespace>PublisherSubscriber.Subscriber</RootNamespace>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="Microsoft.Extensions.Hosting"/>
        <PackageReference Include="RabbitMQ.Client"/>
    </ItemGroup>

    <ItemGroup>
        <ProjectReference Include="..\..\ServiceDefaults\ServiceDefaults.csproj"/>
    </ItemGroup>
</Project>
