<Project Sdk="Microsoft.NET.Sdk.Worker">

    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <Nullable>enable</Nullable>
        <ImplicitUsings>enable</ImplicitUsings>
        <InvariantGlobalization>true</InvariantGlobalization>
        <PublishAot>true</PublishAot>
        <UserSecretsId>dotnet-Producer-553c108f-4ead-47a8-b20f-0bcf9ea56992</UserSecretsId>
        <RootNamespace>ProducerConsumer.Producer</RootNamespace>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="Microsoft.Extensions.Hosting"/>
        <PackageReference Include="RabbitMQ.Client"/>
    </ItemGroup>

    <ItemGroup>
        <ProjectReference Include="..\..\ServiceDefaults\ServiceDefaults.csproj"/>
    </ItemGroup>
</Project>
